apiVersion: 1                                                                                               

contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: admin@localhost
        disableResolveMessage: false


